#+title: Simple Snake game in Python
#+options: num:nil toc:nil author:nil date:nil
#+latex_header: \usepackage{geometry}
#+latex_header: \geometry{left=1cm,right=1cm,marginparwidth=6.8cm, marginparsep=1.2cm,top=0.8cm,bottom=0.5cm}


* Implementation
** Components
  -----
*** Screen
   A representation of the screen. A 2D matrix where X represents columns and Y rows.
*** Snake
   Represented by an array of location-orientation elements. Location is designated as x, y coordinates, and orientation is either 0 or 1, for horizontal and vertical respectively.
   
      + *Location*: Index in the 2d matrix, where /i/ represents column and /j/ row.
      + *Orientation*: Direction to which the head is facing. Represented by one of /E/, /W/, /N/ or /S/, which stands for the four wind directions.
   
*** Fruit
   A list of fruit locations.

** Loop
   1. Get user input.
   2. Record fruit location changes (if any).
   3. Change snake position according to ~input~.
   4. Elongate snake if needed.
   5. render new state.
      
* COMMENT Implementation
  
** Move snake

*** Pseudo code
    Arguments:
            + input :: either RIGHT or LEFT
            + location :: a tuple LOCATION, with LOCATION[0] -> row, and LOCATION[1] -> column.
            + direction :: a string. One of ['e', 'w', 'n', 's'] (wind directions).
    Output: new LOCATION and DIRECTION.
    
    #+begin_src emacs-lisp :exports both :lexical yes
      (defun snk/move (position input)
        "Change POSITION according to user INPUT"
        (interactive "k"))
    #+end_src

